### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [kohei-noda-qcrg/heap_sort_fortran_module_test#1]
I suggest adding the topic `sort`, `sorting`, `heapsort`, `heap-sort` in the About section at https://github.com/kohei-noda-qcrg/heap_sort_fortran_module_test.

**Comment by kohei-noda-qcrg** [comment]
@Beliavsky 
Thanks for your suggest😃 
I added the topics that you suggested to add.
If you have any other suggestions, don't hesitate to contact me.
